[tool.poetry]
name = "nerpii"
version = "0.3.0"
description = "A python library to perform NER on structured data and generate PII with Faker"
authors = ["Clearbox AI <info@clearbox.ai>"]
license = "GPL"
readme = "README.md"
homepage = "https://github.com/Clearbox-AI/nerpii"
repository = "https://github.com/Clearbox-AI/nerpii"
packages = [{include = "nerpii"}]

[tool.poetry.dependencies]
python = "^3.10"
pandas = ">=2.2,<4"
numpy = ">=1.26"
presidio-analyzer = ">=2.2.355,<3"
transformers = ">=4.40,<6"
faker = ">=30"
gender-guesser = "^0.4.0"
spacy = ">=3.7.2,<4"
torch = ">=2.2"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29"
pytest = "^9.0.3"
flake8 = "^7.1"
flake8-import-order = "^0.19.2"
flake8-black = "^0.4.0"
black = ">=24.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

